---
layout: cv
title: Kase Kolberg's CV
---
# Kase Kolberg
Financial Economics Major

<div id="webaddress">
<a href="kasekolberg@gmail.com">kasekolberg@gmail.com</a>
</div>

## Education
### Brigham Young University - Idaho	Rexburg, ID
Bachelor of Science in Financial Economics - Minor in Finance	Expected April 2025

•	GPA: 3.34

•	Teacher’s assistant – Spreadsheet Analysis – graded 18 Excel projects for 30 students

•	Coursework: Macro & Microeconomics, Financial & Managerial Accounting, Financial Management, Spreadsheet Analysis, Statistics, Managerial Economics, Financial Analytics, Advanced Spreadsheet Application, Econometrics

## Experience
#### Rove Pest Control	St Paul, MN
#### Financial/Data Analyst Intern	May 2024-Present
•	Created VBA program to automate monthly fuel transaction reports, improving reporting efficiency

•	Visualized large datasets to identify trends, enabling company to make better decisions and implement changes

•	Generated paystubs for sales team by sorting data in Excel, ensuring accurate and timely distribution

•	Analyzed call data to detect 18 inactive numbers, optimizing the call routing process for better customer support

#### Greenway Pest	Albuquerque, NM
#### Pest Control Technician	Apr 2022-Aug 2023
•	Trained six employees in proper protocols and procedures to efficiently service houses

•	Communicated concerns of customers with sales team to improve retention and satisfaction

•	Interacted with 1,000+ customers, ensuring contracts were understood and services were provided efficiently 

#### Green Tree Apartments	Bozeman, MT
#### Apartment Renovator	May 2020-Jun 2020
•	Collaborated with five others to complete apartment renovation tasks for four apartments

•	Accurately recorded and reported job progress each day to apartment managers

•	Demonstrated strong work ethic by consistently working 40 hours per week

## LEADERSHIP & SERVICE
#### The Church of Jesus Christ of Latter-day Saints	Santa Cruz, Bolivia & Philadelphia, PA
#### Full-time Volunteer Representative	Jul 2019- Jul 2021
•	Organized presentations, meetings, and programs focused on effective instruction and service

•	Led five volunteers in discussions concerning work efficiency and methods of increasing success of service

•	Taught English and religion to dozens of people both in person and virtually

#### Boy Scouts of America	St Paul, MN
#### Boy Scout/Eagle Scout	Mar 2012-Apr 2019
•	Completed over 21 merit badges and all requirements to earn Eagle Scout ranking 
•	Oversaw planning and supervised over 10 people on the building of nature walkway for Eagle project

## SKILLS/INTERESTS
•	Languages: English and proficient in Spanish

•	Computer skills: R (basic), SQL (basic), Python (basic), Power BI, Excel- functions, Pivot Tables, Macros, VBA

•	Interests: stocks, breakdancing, weightlifting, singing

•	Member of Investment Society at BYU-I




<!-- ### Footer

Last updated: December 2024 -->